//
//  en.swift
//  Flowers
//
//  Created by Jozsef Romhanyi on 20.09.15.
//  Copyright © 2015 Jozsef Romhanyi. All rights reserved.
//


let enDictionary: [TextConstants: String] = [
    .TCAktLanguage:      "en",
    .TCLevel:            "Level%",
    .TCLevelScore:       "Levelscore%",
    .TCGameScore:        "Score: % / % Cards",
    .TCScore:            "Score",
    .TCTime:             "used time: %",
    .TCActScore:         "Score of last Game: ",
    .TCBestScore:        "Best Score",
    .TCTargetScore:      "target Score:",
    .TCGameLost:         "you lost!",
    .TCGameLost3:        "You lose 3 times. Previous level starts.",
    .TCTargetNotReached: "target not reached",
    .TCSpriteCount:      "Count of Flowers:",
    .TCCardCount:        "Count of Cards:",
    .TCReturn:           "Return",
    .TCOK:               "OK",
    .TCGameComplete:     "Game % completed!",
    .TCNoMessage:        "no Message",
    .TCTimeout:          "timeout",
    .TCGameOver:         "Game Over",
    .TCCongratulations:  "Congratulations ",
    .TCName:             "List of player",
    .TCVolume:           "Lautstärke",
    .TCCountHelpLines:   "Count helplines",
    .TCLanguage:         "Language",
    .TCEnglish:          "English (English)",
    .TCGerman:           "Deutsch (German)",
    .TCHungarian:        "Magyar (Hungarian)",
    .TCRussian:          "Русский (Russian)",
    .TCCancel:           "Cancel",
    .TCDone:             "Done",    
    .TCModify:           "Modify",
    .TCDelete:           "Delete",
    .TCNewName:          "New Player",
    .TCChooseLanguage:   "Choose a language",
    .TCPlayer:           "Player",
    .TCGameModus:        "Gamemodus",
    .TCSoundVolume:      "Sound Volume",
    .TCMusicVolume:      "Musik Volume",
    .TCStandardGame:     "Game with Flowers",
    .TCCardGame:         "Game with Cards",
    .TCPreviousLevel:    "Previous Level",
    .TCNextLevel:        "next level",
    .TCNewGame:          "New Game",
    .TCGameAgain:        "Restart Game",
    .TCChooseGame:       "Choose Please:",
    .TCTippCount:        "Number of possible steps: ",
    .TCStatistics:       "Statistics of game % on Level %",
    .TCActTime:          "Time for game: ",
    .TCBestTimeForLevel: "Best time for this Level: ",
    .TCBestTime:         "Best time",
    .TCAllTimeForLevel:  "Total time for this level: ",
    .TCAllTime:          "Time",
    .TCCountPlaysForLevel:"Until now played % games",
    .TCCountPlays:        "Games",
    .TCCountCompetitions: "Competitions",
    .TCCountVictorys:     "Victory / Defeat",
    .TCGameCompleteWithBestScore: "New score record at level %!",
    .TCGameCompleteWithBestTime:  "New time record at level %!",
    .TCGuest:            "Guest",
    .TCAnonym:           "Anonymus",
    .TCStatistic:        "Statistics",
    .TCPlayerStatisticHeader: "Statistics for %, level: %",
    .TCStatisticOfGame:  "Statistic of game Nr. %",
    .TCBestScoreOfGame:   "Best score %  %",
    .TCYourScore:           "Your score %",
    .TCYouAreTheBest:    "You are the Best with score %",
    .TCGameNumber:       "Game number: %",
    .TCChooseGameNumber: "Choose a game",
    .TCPlayerStatistic:  "Player statistic",
    .TCGameStatistic:    "Game statistic",
    .TCCompetition:      "Competition",
    .TCGame:             "Game",
    .TCChoosePartner:    "Choose an opponent:",
    .TCWantToPlayWithYou:"% want play with you!",
    .TCOpponent:          "Opponent%",
    .TCOpponentHasFinished: "% has finished the Game #%!\r\n" +
                            "his bonus: %\r\n" +
                            "his score : %\r\n" +
                            "your score: %\r\n ",
    .TCHeWon:               "% won % - %!\r\n" +
                            "Sorry :-(",
    .TCYouWon:              "You won % - %! \r\n" +
                            "Congratulations!!!",
    .TCYouHaveFinished: "You have finished the Game #%!\r\n" +
                        "your bonus: %\r\n" +
                        "your score : %\r\n" +
                        "% score: %\r\n ",
    .TCOpponentNotPlay: "% does not want to play with you!",
    .TCGameArt:         "Type",
    .TCVictory:         "Victory",
    .TCStart:           "Start",
]
