//
//  en.swift
//  Flowers
//
//  Created by Jozsef Romhanyi on 20.09.15.
//  Copyright © 2015 Jozsef Romhanyi. All rights reserved.
//


let enDictionary: [TextConstants: String] = [
    .TCAktLanguage:      "en",
    .TCLevel:            "Level",
    .TCLevelScore:       "Levelscore:",
    .TCGameScore:        "Gamescore: ",
    .TCActScore:         "Score of last Game: ",
    .TCBestScore:        "Best Score",
    .TCTargetScore:      "target Score:",
    .TCTimeLeft:         "used time:",
    .TCGameLost:         "you lost!",
    .TCGameLost3:        "You lose 3 times. Previous level starts.",
    .TCTargetNotReached: "target not reached",
    .TCSpriteCount:      "Count of Flowers:",
    .TCCardCount:        "Count of Cards:",
    .TCReturn:           "Return",
    .TCOK:               "OK",
    .TCGameComplete:     "Game completed!",
    .TCNoMessage:        "no Message",
    .TCTimeout:          "timeout",
    .TCGameOver:         "Game Over",
    .TCCongratulations:  "Congratulations ",
    .TCName:             "List of player",
    .TCVolume:           "Lautstärke",
    .TCCountHelpLines:   "Count helplines",
    .TCLanguage:         "Language",
    .TCEnglish:          "English (English)",
    .TCGerman:           "Deutsch (German)",
    .TCHungarian:        "Magyar (Hungarian)",
    .TCRussian:          "Русский (Russian)",
    .TCCancel:           "Cancel",
    .TCDone:             "Done",    
    .TCModify:           "Modify",
    .TCDelete:           "Delete",
    .TCNewName:          "New Player",
    .TCChoose:           "Choose",
    .TCPlayer:           "Player",
    .TCGameModus:        "Gamemodus",
    .TCSoundVolume:      "Sound Volume",
    .TCMusicVolume:      "Musik Volume",
    .TCStandardGame:     "Game with Flowers",
    .TCCardGame:         "Game with Cards",
    .TCPreviousLevel:    "Previous Level",
    .TCNextLevel:        "next level",
    .TCNewGame:          "New Game",
    .TCGameAgain:        "Restart Game",
    .TCChooseGame:       "Choose Please:",
    .TCTippCount:        "Number of possible steps: ",
    .TCStatistics:       "Statistics of the Level %",
    .TCActTime:          "Time for last game: ",
    .TCBestTimeForLevel: "Best time for this Level: ",
    .TCBestTime:         "Best time",
    .TCAllTimeForLevel:  "Total time for this level: ",
    .TCAllTime:          "Total time",
    .TCCountPlaysForLevel:"Until now played % games",
    .TCCountPlays:        "Play counter",
    .TCGameCompleteWithBestScore: "New score record at level %!",
    .TCGameCompleteWithBestTime:  "New time record at level %!",
    .TCGuest:            "Guest",
    .TCAnonym:           "Anonymus",
    .TCStatistic:        "Statistics",
    .TCPlayerStatisticHeader: "Statistics for %",
]
