//
//  hu.swift
//  Flowers
//
//  Created by Jozsef Romhanyi on 20.09.15.
//  Copyright © 2015 Jozsef Romhanyi. All rights reserved.
//


let huDictionary: [TextConstants: String] = [
    .TCAktLanguage:      "hu",
    .TCLevel:            "Szint",
    .TCLevelScore:       "Pontszám: ",
    .TCGameScore:        "Játék pontszám: ",
    .TCActScore:         "Az utolsó játék pontszáma: ",
    .TCTargetScore:      "Elérendö pontszám: ",
    .TCTimeLeft:         "Elhasznált idő:",
    .TCGameLost:         "Vesztettél!",
    .TCGameLost3:        "3-szor vesztettél. Előző szintre vissza!!!",
    .TCTargetNotReached: "A cél nem teljesült",
    .TCSpriteCount:      "Virágok száma:",
    .TCCardCount:        "Kártyalapok száma:",
    .TCReturn:           "Vissza",
    .TCOK:               "OK",
    .TCGameComplete:     "Játék befejezve!",
    .TCNoMessage:        "nem létező üzenet",
    .TCTimeout:          "Lejárt az időd",
    .TCGameOver:         "Vesztettél",
    .TCCongratulations:  "Gratulálok ",
    .TCName:             "Játékosok listája",
    .TCVolume:           "Hangerő",
    .TCCountHelpLines:   "Segédvonalak száma",
    .TCLanguage:         "Nyelv",
    .TCEnglish:          "English (Angol)",
    .TCGerman:           "Deutsch (Német)",
    .TCHungarian:        "Magyar (Magyar)",
    .TCRussian:          "Русский (Orosz)",
    .TCCancel:           "Mégsem",
    .TCDone:             "Kész",
    .TCModify:           "Módosítás",
    .TCDelete:           "Eltávolítás",
    .TCNewName:          "Új játékos",
    .TCChooseLanguage:   "Nyelv kiválasztás",
    .TCPlayer:           "Játékos",
    .TCGameModus:        "Játékmód",
    .TCSoundVolume:      "Háttérzajok hangerő",
    .TCMusicVolume:      "Zene hangerő",
    .TCStandardGame:     "Játék virágokkal",
    .TCCardGame:         "Kártyajáték",
    .TCPreviousLevel:    "Előző szint",
    .TCNextLevel:        "Következő szint",
    .TCNewGame:          "Új játék",
    .TCGameAgain:        "Újra játszom",
    .TCChooseGame:       "Válassz:",
    .TCTippCount:        "Lehetséges lépések száma: ",
    .TCStatistics:       "A(z) %. szint statisztikája ",
    .TCActTime:          "Utolsó játék időtartama: ",
    .TCBestTimeForLevel: "A szint legjobb ideje: ",
    .TCBestTime:         "Legjobb idő",
    .TCAllTimeForLevel:  "A szint teljes játékideje: ",
    .TCAllTime:          "Teljes játékidő",
    .TCCountPlaysForLevel: "Eddig % játékot játszottál",
    .TCCountPlays:        "Játék számláló",
    .TCBestScore:        "Legjobb pontszám",
    .TCGameCompleteWithBestScore: "Új pontszám rekord a(z) % szinten!",
    .TCGameCompleteWithBestTime:  "Legjobb idő a(z) % szinten",
    .TCGuest:            "Vendég",
    .TCAnonym:           "Anonymus",
    .TCStatistic:        "Statisztikák",
    .TCPlayerStatisticHeader: "% statisztikái",
]
