# Uncomment this line to define a global platform for your project
# platform :ios, ‘9.0’
# Uncomment this line if you're using Swift
# use_frameworks!

xcodeproj ‘Flowers.xcodeproj'
workspace ‘Flowers.xcworkspace'
platform :ios, ‘9.0’

source 'https://github.com/artsy/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'


def shared_pods
      pod 'RealmSwift', '>= 0.92.3'
end
use_frameworks!

target 'Flowers' do
shared_pods
end

target 'FlowersTests' do
shared_pods
end

target 'FlowersUITests' do
shared_pods
end



