//
//  ru.swift
//  Flowers
//
//  Created by Jozsef Romhanyi on 20.09.15.
//  Copyright © 2015 Jozsef Romhanyi. All rights reserved.
//


let ruDictionary: [TextConstants: String] = [
    .TCAktLanguage:      "ru",
    .TCLevel:            "Уровень",
    .TCLevelScore:       "Очки:",
    .TCGameScore:        "Очки :",
    .TCActScore:         "Очки последней игры: ",
    .TCBestScore:        "Лучшие очки",
    .TCTargetScore:      "получить очки: ",
    .TCTimeLeft:         "используемое время:",
    .TCGameLost:         "ты проиграл!",
    .TCGameLost3:        "Ты проиграл в 3 раза! Назад к предыдущему уровню!",
    .TCTargetNotReached: "Цель не достигнутa",
    .TCSpriteCount:      "количество цветов:",
    .TCCardCount:        "количество карт:",
    .TCReturn:           "назад",
    .TCOK:               "OK",
    .TCGameComplete:     "Игра завершена!",
    .TCNoMessage:        "сообщение не найдёно",
    .TCTimeout:          "Время закончилось",
    .TCGameOver:         "Игра проиграна",
    .TCCongratulations:  "Поздравляю ",
    .TCName:             "Список игроков",
    .TCVolume:           "Громкость",
    .TCCountHelpLines:   "кол. вспомогательных линий",
    .TCLanguage:         "Язык",
    .TCEnglish:          "English (Английский)",
    .TCGerman:           "Deutsch (Немецкий)",
    .TCHungarian:        "Magyar (Венгерский)",
    .TCRussian:          "Русский (Русский)",
    .TCCancel:           "Отменить",
    .TCDone:             "Готово",
    .TCModify:           "Изменить",
    .TCDelete:           "Удалить",
    .TCNewName:          "Новый игрок",
    .TCChooseLanguage:   "Выбoр языка",
    .TCPlayer:           "Игрок",
    .TCGameModus:        "Тип игры",
    .TCSoundVolume:      "Громкость звука",
    .TCMusicVolume:      "Громкость музыки",
    .TCStandardGame:     "Игра с цветами",
    .TCCardGame:         "Игра с картами",
    .TCPreviousLevel:    "предыдущий уровень",
    .TCNextLevel:        "следующий уровень",
    .TCNewGame:          "Новая игра",
    .TCGameAgain:        "Повторить игру",
    .TCChooseGame:       "Выберите пожалуйста:",
    .TCTippCount:        "Kоличество возможных ходов: ",
    .TCStatistics:       "Статистика уровня %",
    .TCActTime:          "Продолжительность последней игры: ",
    .TCBestTimeForLevel: "Лучшее время уровня: ",
    .TCBestTime:         "Лучшее время",
    .TCAllTimeForLevel:  "Полное время уровня: ",
    .TCAllTime:          "Полное время",
    .TCCountPlaysForLevel: "До сих пор % игр",
    .TCCountPlays:        "Счетчик игр",
    .TCGameCompleteWithBestScore: "Новый рекорд очков на уровне %!",
    .TCGameCompleteWithBestTime:  "Новый рекорд времени на уровне % ",
    .TCGuest:            "Гость",
    .TCAnonym:           "Anonymus",
    .TCStatistic:        "Статистика",
    .TCPlayerStatisticHeader: "Статистики игрока %",
]
